spring:
  profiles:
    active: dev #开发环境
    #active: production #生成环境
  banner:
    charset: UTF-8
  encoding:
        charset: UTF-8
        enabled: UTF-8
        force: UTF-8
        encoding: UTF-8
# Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 2000
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5
    # 连接池中的最大空闲连接
      max-idle: 20
    # 连接池中的最小空闲连接
      min-idle: 10
#------------------------ redis end









